name: Reuseable Workflow

on:
  workflow_call:
    inputs:
      artifact-id:
        description: The id of the artifact files
        required: true
        type: string
        # default: dist-files
    secrets:
      some-secret:
        required: true
    outputs:
      result:
        description: The result of the deployment job
        value: ${{ jobs.deploy.outputs.outcome }}
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      outcome: ${{ steps.set-result.outputs.step-result }}
    steps:
      - name: Output Information
        run: echo "Starting process..."
      - name: Output Secret
        run: echo ${{ secrets.some-secret }}
      - name: Get build artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-id }}
      - name: Output contents
        run: ls
      - name: Deploy
        run: echo "Deploying..."
      - name: Set Result output
        id: set-result
        run: echo "step-result=success" >> $GITHUB_OUTPUT